#Veltgop#1 By MengXiaoBai
#本插件为Veltgop内部插件开发的第一部分，请多多支持！
#屏蔽的内容
NoWordList:
  - 'nmsl'
  - '傻逼'
#玩家发送屏蔽词后提示的信息(支持颜色代码&,支持多行，必须按照本格式写，不然会导致无法读取与报错)
Message:
  - '&c你输入了本服务器的违禁词，您被禁止发言10分钟！如您有异议，请B站咨询管理员'
