#Veltgop#1 By MengXiaoBai
#本插件为Veltgop内部插件开发的第一部分，请多多支持！
#屏蔽的内容
#请注意屏蔽的内容如含有字母所有字母必须为小写！！插件会把大写转为小写！！！不要含空格，插件会过滤空格！！！
NoWordList:
  - 'nmsl'
  - '傻逼'
#玩家发送屏蔽词后提示的信息(支持颜色代码&，必须按照本格式写，不然会导致无法读取与报错)
Message: '&c你输入了本服务器的违禁词，您被禁止发言10分钟！如您有异议，请B站咨询管理员'
#玩家被禁言后尝试发送后提示的信息(支持颜色代码&，必须按照本格式写，不然会导致无法读取与报错)
MutedMessage: '&c您已被管理员禁言！'
