#Veltgop#1 By MengXiaoBai

#是否开启自动更新
autoupdate: false
#屏蔽的内容
#请注意屏蔽的内容如含有字母所有字母必须为小写！！插件会把大写转为小写！！！不要含空格，插件会过滤空格！！！
NoWordList:
  - 'nmsl'
  - '傻逼'
#玩家发送违禁词是否通知管理
noticeadmin: true
#玩家发送屏蔽词后提示的信息(支持颜色代码&，必须按照本格式写，不然会导致无法读取与报错)
Message: '&c你输入了本服务器的违禁词，您被禁止发言10分钟！如您有异议，请B站咨询管理员'
#玩家被禁言后尝试发送后提示的信息(支持颜色代码&，必须按照本格式写，不然会导致无法读取与报错)
MutedMessage: '&c您已被管理员禁言！'
#玩家触发违禁词后进行的惩罚
#1为系统内置禁言系统，必须安装Luckperms插件
#2为外置封禁系统，需使用Essentials/AdvancedBan/LiteBans三选一插件
#3为不管不顾
Bansway: 2
#选择Bansway为2的惩罚类型
#1为踢出
#2为封禁
#3为禁言
#4为警告
Banstype: 3

